config/routes.rb
Rails.application.routes.draw do
  get 'labels/index'
  get 'labels/weapons'
  get 'labels/armor'
  get 'labels/anyspell'
  get 'labels/instrument'
  get 'labels/gearpack'
  get 'labels/artisan'

  resources :characters
  resources :races, param: :name, only: [ :show ]
  resources :subraces, param: :name, only: [ :show ]
  resources :player_classes, param: :name, only: [ :show ]
  resources :subclasses, param: :name, only: [ :show ]
  resources :backgrounds, param: :name, only: [ :show ]
  resources :class_spell_lists, param: :name, only: [ :show ]
  resources :weapons, param: :wep_type, only: [ :show ]
  devise_for :users

  root 'home#index'
  get 'creation/sheet'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/armor.rb
class Armor < ApplicationRecord
end

app/models/background.rb
class Background < ApplicationRecord
  serialize :equipment_choices, Hash
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash

  has_many :characters

  def to_param
    name
  end
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :race
  belongs_to :subrace
  belongs_to :player_class
  belongs_to :subclass
  belongs_to :background
  belongs_to :user
end

app/models/class_spell_list.rb
class ClassSpellList < ApplicationRecord
  has_and_belongs_to_many :spells
  serialize :atk_dmg, Hash

  def to_param
    name
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_and_belongs_to_many :gearpacks
end

app/models/equipment_gearpack.rb
class EquipmentGearpack < ApplicationRecord
end

app/models/feat.rb
class Feat < ApplicationRecord
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash
  has_many :characters
end

app/models/gearpack.rb
class Gearpack < ApplicationRecord
  has_and_belongs_to_many :equipment
  has_and_belongs_to_many :tools
end

app/models/gearpacks_tool.rb
class GearpacksTool < ApplicationRecord
end

app/models/player_class.rb
class PlayerClass < ApplicationRecord
  serialize :features, Hash
  serialize :custom, Hash
  serialize :equipment_choices, Hash
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash

  has_many :subclasses
  has_many :characters

  def to_param
    name
  end
end

app/models/race.rb
class Race < ApplicationRecord
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash

  has_many :characters
  has_many :subraces

  def to_param
    name
  end
end

app/models/spell.rb
class Spell < ApplicationRecord
  serialize :atk_dmg, Hash
  has_and_belongs_to_many :class_spell_lists
end

app/models/subclass.rb
class Subclass < ApplicationRecord
  serialize :custom, Hash
  serialize :features, Hash
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash
  serialize :equipment_choices, Hash

  belongs_to :player_class
  has_many :characters

  def to_param
    name
  end
end

app/models/subrace.rb
class Subrace < ApplicationRecord
  serialize :extra_spells, Hash
  serialize :specific_spells, Hash
  serialize :custom_mods, Hash

  belongs_to :race
  has_many :characters

  def to_param
    name
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_and_belongs_to_many :gearpacks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :characters
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  def to_param
    wep_type
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to character_url(@character), notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_url(@character), notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:race_id, :player_class_id, :background_id, :feat_id, :user_id, :player_name, :char_name, :age, :height, :eyes, :hair, :skin, :gender, :description, :languages, :weapon_prof, :armor_prof, :tool_prof, :skill_prof, :expertise, :size, :speed, :hp_max, :equipment, :gold, :silver, :copper, :spells, :spell_slots, :trait, :ideal, :bond, :flaw, :bkgd_specialty)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/creation_helper.rb
module CreationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/characters/_character.html.erb
<div id="<%= dom_id character %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Race:</strong>
    <%= character.race_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Player class:</strong>
    <%= character.player_class_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Background:</strong>
    <%= character.background_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Feat:</strong>
    <%= character.feat_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= character.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Player name:</strong>
    <%= character.player_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Char name:</strong>
    <%= character.char_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Age:</strong>
    <%= character.age %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Height:</strong>
    <%= character.height %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Eyes:</strong>
    <%= character.eyes %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hair:</strong>
    <%= character.hair %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Skin:</strong>
    <%= character.skin %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Gender:</strong>
    <%= character.gender %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= character.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Languages:</strong>
    <%= character.languages %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Weapon prof:</strong>
    <%= character.weapon_prof %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Armor prof:</strong>
    <%= character.armor_prof %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Tool prof:</strong>
    <%= character.tool_prof %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Skill prof:</strong>
    <%= character.skill_prof %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Expertise:</strong>
    <%= character.expertise %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Size:</strong>
    <%= character.size %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Speed:</strong>
    <%= character.speed %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hp max:</strong>
    <%= character.hp_max %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Equipment:</strong>
    <%= character.equipment %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Gold:</strong>
    <%= character.gold %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Silver:</strong>
    <%= character.silver %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Copper:</strong>
    <%= character.copper %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Spells:</strong>
    <%= character.spells %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Spell slots:</strong>
    <%= character.spell_slots %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Trait:</strong>
    <%= character.trait %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ideal:</strong>
    <%= character.ideal %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bond:</strong>
    <%= character.bond %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Flaw:</strong>
    <%= character.flaw %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bkgd specialty:</strong>
    <%= character.bkgd_specialty %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this character", character, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this character', edit_character_path(character), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/characters/_form.html.erb
<%= form_with(model: character, class: "contents") do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :race_id %>
    <%= form.number_field :race_id, class: "formfield formid" %>
  </div>

  <div class="my-5">
    <%= form.label :player_class_id %>
    <%= form.number_field :player_class_id, class: "formfield formid" %>
  </div>

  <div class="my-5">
    <%= form.label :background_id %>
    <%= form.number_field :background_id, class: "formfield formid" %>
  </div>

  <div class="my-5">
    <%= form.label :feat_id %>
    <%= form.number_field :feat_id, class: "formfield formid" %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, class: "formfield formid" %>
  </div>

  <div class="my-5">
    <%= form.label :player_name %>
    <%= form.text_field :player_name, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :char_name %>
    <%= form.text_field :char_name, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :age %>
    <%= form.text_field :age, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :height %>
    <%= form.text_field :height, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :eyes %>
    <%= form.text_field :eyes, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :hair %>
    <%= form.text_field :hair, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :skin %>
    <%= form.text_field :skin, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "formfield formentry" %>
  </div>

  <div class="my-5">
    <%= form.label :languages %>
    <%= form.text_field :languages, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :weapon_prof %>
    <%= form.text_field :weapon_prof, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :armor_prof %>
    <%= form.text_field :armor_prof, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :tool_prof %>
    <%= form.text_field :tool_prof, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :skill_prof %>
    <%= form.text_field :skill_prof, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :expertise %>
    <%= form.text_field :expertise, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :size %>
    <%= form.text_field :size, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :speed %>
    <%= form.number_field :speed, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :hp_max %>
    <%= form.number_field :hp_max, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :equipment %>
    <%= form.text_field :equipment, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :gold %>
    <%= form.number_field :gold, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :silver %>
    <%= form.number_field :silver, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :copper %>
    <%= form.number_field :copper, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :spells %>
    <%= form.text_field :spells, class: "formfield formselect" %>
  </div>

  <div class="my-5">
    <%= form.label :spell_slots %>
    <%= form.number_field :spell_slots, class: "formfield formcalc" %>
  </div>

  <div class="my-5">
    <%= form.label :trait %>
    <%= form.text_field :trait, class: "formfield formselect" %>
  </div>

  <div class="my-5">
    <%= form.label :ideal %>
    <%= form.text_field :ideal, class: "formfield formselect" %>
  </div>

  <div class="my-5">
    <%= form.label :bond %>
    <%= form.text_field :bond, class: "formfield formselect" %>
  </div>

  <div class="my-5">
    <%= form.label :flaw %>
    <%= form.text_field :flaw, class: "formfield formselect" %>
  </div>

  <div class="my-5">
    <%= form.label :bkgd_specialty %>
    <%= form.text_field :bkgd_specialty, class: "formfield formselect" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing character</h1>

  <%= render "form", character: @character %>

  <%= link_to "Show this character", @character, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/characters/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Characters</h1>
    <%= link_to 'New character', new_character_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="characters" class="min-w-full">
    <%= render @characters %>
  </div>
</div>

app/views/characters/new.html.erb
<div class="mx-auto md:w-2/3 w-full text-white font-inter font-bold">
  <h1 class="font-bold text-4xl">New character</h1>

  <%= render "form", character: @character %>

  <%= link_to 'Back to characters', characters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/characters/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @character %>

    <%= link_to 'Edit this character', edit_character_path(@character), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this character', character_path(@character), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to characters', characters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>